---
name: Autobuild README
on:
  push:
    branches: [main]
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to main branch
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Cache dependencies and build outputs
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: LFM_API_KEY=${{secrets.LFM_API_KEY}} node index.js
      - name: Commit and push new README.md
        run: |-
          git diff
          git config --global user.email "${{secrets.GLOBAL_USER_EMAIL}}"
          git config --global user.name "${{secrets.GLOBAL_USER_NAME}}"
          git commit -a -m "README Bot Run" || exit 0
          git push
